-- =====================================================
-- SEED SISWA INTERVENSI (128 siswa)
-- Login: Nama Lengkap + Kode Password (6 huruf random)
-- =====================================================

-- 7h (32 siswa)
INSERT INTO siswa_intervensi (name, kode_password_hash) VALUES
  ('Abian Dwi Fernando', crypt('wyazps', gen_salt('bf'))),
  ('Achmad Wahyu Ferriansyah', crypt('ruresj', gen_salt('bf'))),
  ('Ahmad Ainul Yaqin', crypt('nrfbwo', gen_salt('bf'))),
  ('Ahmad Hanan Nur Rafif', crypt('makwed', gen_salt('bf'))),
  ('Aqila Jihan Zahra', crypt('zttdsz', gen_salt('bf'))),
  ('Aqila Rahma Fitri', crypt('banbnl', gen_salt('bf'))),
  ('Arvin Pratama', crypt('jwzpxl', gen_salt('bf'))),
  ('Auryn Birra Shofwah Alazalya', crypt('kkohob', gen_salt('bf'))),
  ('Chuzaimatus Salma Awatif', crypt('lfakko', gen_salt('bf'))),
  ('Fathia Almahyra Rafifa', crypt('axvxhc', gen_salt('bf'))),
  ('Fatimah Iffah Rosyadah', crypt('qmugrr', gen_salt('bf'))),
  ('Fina Fittrotul Fatimah', crypt('jnuhfe', gen_salt('bf'))),
  ('Haikal Keisha Rahmat', crypt('trnlsz', gen_salt('bf'))),
  ('Muchammad Yahya', crypt('erqzoj', gen_salt('bf'))),
  ('Muhamad Burhan Haviz Ramadani', crypt('xargcj', gen_salt('bf'))),
  ('Muhammad Alby Elvaro Azhmi', crypt('zubtpd', gen_salt('bf'))),
  ('Muhammad Azra Kasyafani Zarrin', crypt('kfkcfm', gen_salt('bf'))),
  ('Muhammad Defan Maulana', crypt('eojuhu', gen_salt('bf'))),
  ('Muhammad Dzaidan Darussalam', crypt('birzgl', gen_salt('bf'))),
  ('Muhammad Ibnu Sulaiman', crypt('gtbkkq', gen_salt('bf'))),
  ('Nabila Azmi Khairunisa', crypt('reqjem', gen_salt('bf'))),
  ('Nizam Zainuri', crypt('tmnjgo', gen_salt('bf'))),
  ('Nurul Husna Najmi Subaiqoh', crypt('pvvotx', gen_salt('bf'))),
  ('Radian Lesmana Panca Yoga', crypt('qgxlag', gen_salt('bf'))),
  ('Raisyeilla Atika Pratiwi', crypt('hfvqiz', gen_salt('bf'))),
  ('Reisya Putri Maulidina', crypt('acsrmn', gen_salt('bf'))),
  ('Vanesa Ria Cahyani', crypt('uvnwmo', gen_salt('bf'))),
  ('Viky Nur Ikhsan', crypt('jugokb', gen_salt('bf'))),
  ('Wahyu Aulia Saptia Sari', crypt('ecjsxp', gen_salt('bf'))),
  ('Wanda Cahya Alfitrani', crypt('akgotz', gen_salt('bf'))),
  ('Yasmin Mayrizna Salwa', crypt('hlfidy', gen_salt('bf'))),
  ('Yollanda Reza Nur Aisyah', crypt('hxisie', gen_salt('bf')));

-- 7c (32 siswa)
INSERT INTO siswa_intervensi (name, kode_password_hash) VALUES
  ('Alfarizi Putra Rahman', crypt('ycqepc', gen_salt('bf'))),
  ('Adinda Kanza Alzhara', crypt('fxscas', gen_salt('bf'))),
  ('Ahmad Dani Santoso', crypt('hsfqkc', gen_salt('bf'))),
  ('Ahmad Yazid Al Fatih', crypt('qzztay', gen_salt('bf'))),
  ('Air Nakla Adinata Putra', crypt('itkazi', gen_salt('bf'))),
  ('Al Kaila Desvita Zaharani', crypt('cjfwnx', gen_salt('bf'))),
  ('Alviando Fahrizal Mauludin', crypt('dxcmxd', gen_salt('bf'))),
  ('Aqilla Mufida Zahwa', crypt('pnqknw', gen_salt('bf'))),
  ('Arya Abhiseka Wibowo', crypt('wvbndi', gen_salt('bf'))),
  ('Bagus Dwi Prastyo', crypt('aoofir', gen_salt('bf'))),
  ('Cinta Azkya Azkadina', crypt('kixasf', gen_salt('bf'))),
  ('Earlyta Aurelia Fadila', crypt('ziykxr', gen_salt('bf'))),
  ('Fitria Anggraeni', crypt('mcwzsb', gen_salt('bf'))),
  ('Hafiz Agung Ahmadian', crypt('bwfhzd', gen_salt('bf'))),
  ('Joaquin Abinaya Sakha Balidin', crypt('kvhfzs', gen_salt('bf'))),
  ('Keyza Putri Zavira', crypt('rssjws', gen_salt('bf'))),
  ('Khoirul Andi Firmansyah', crypt('jevlvt', gen_salt('bf'))),
  ('Melodi Bergian Rabani', crypt('kiasip', gen_salt('bf'))),
  ('Moch Ibnu Athoillah', crypt('zdmudb', gen_salt('bf'))),
  ('Muhamad Nizam', crypt('gwzqtl', gen_salt('bf'))),
  ('Muhamad Riski Avrilio', crypt('yqgmze', gen_salt('bf'))),
  ('Muhammad Rizqi Habibi', crypt('wiejaz', gen_salt('bf'))),
  ('Muhammad Teuku Afif Ar Rasyah', crypt('rpivyd', gen_salt('bf'))),
  ('M. Revan Assabil Azzam', crypt('qeynpm', gen_salt('bf'))),
  ('Radityan Rifky Adinata', crypt('anwwtj', gen_salt('bf'))),
  ('Rahmah Embun Zahra', crypt('mrlhht', gen_salt('bf'))),
  ('Reno Komala Putra', crypt('fxrwba', gen_salt('bf'))),
  ('Risma Amelia Ramadhani', crypt('ieofcv', gen_salt('bf'))),
  ('Salsa Dwi Anggraini', crypt('ewctky', gen_salt('bf'))),
  ('Silvia Azzahra Husna', crypt('ahjlbo', gen_salt('bf'))),
  ('Silvia Roviatus Khoirunisa', crypt('ngrkmu', gen_salt('bf'))),
  ('Siti Nur Mas Khariroh', crypt('peekbh', gen_salt('bf')));

-- 8b (32 siswa)
INSERT INTO siswa_intervensi (name, kode_password_hash) VALUES
  ('Achmad Devan Satria', crypt('qsuvqg', gen_salt('bf'))),
  ('Ahmad Harun Ar-Rasyid Putra Wicaksono', crypt('bglqmv', gen_salt('bf'))),
  ('Alifia Rahma Azizah', crypt('awoyhw', gen_salt('bf'))),
  ('Azka Alvaro', crypt('bujdra', gen_salt('bf'))),
  ('Cahyo Sugi Apriliansyah', crypt('pnuhwk', gen_salt('bf'))),
  ('Chika Alkarina Aura Putri', crypt('hvthdg', gen_salt('bf'))),
  ('Egi Aditya Prayogi', crypt('kvapyw', gen_salt('bf'))),
  ('Fanesa Eka Nanda Cahyani', crypt('sneraz', gen_salt('bf'))),
  ('Herlisa Amelia Putri', crypt('gjciut', gen_salt('bf'))),
  ('Ilham Raffa Firdaus', crypt('actmsn', gen_salt('bf'))),
  ('Jessica Ayunda Putri', crypt('rgazrx', gen_salt('bf'))),
  ('Junna Rasikah Syafat', crypt('ueejbj', gen_salt('bf'))),
  ('Khalista Putri Yanianti', crypt('xyebqc', gen_salt('bf'))),
  ('Khanza Eryna Saphira', crypt('ilfmvw', gen_salt('bf'))),
  ('Luluk Anjarwani', crypt('ogqpck', gen_salt('bf'))),
  ('M Nicola El Insi', crypt('lheqkj', gen_salt('bf'))),
  ('M. Gilang Bima Pratama', crypt('fchomv', gen_salt('bf'))),
  ('Meisya Shakila Putri Aisya', crypt('zuluqr', gen_salt('bf'))),
  ('Metha Jihan Andini', crypt('oegpxv', gen_salt('bf'))),
  ('Mohammad Nizam Alridho', crypt('zghdjn', gen_salt('bf'))),
  ('Muhammad Alfariz Wagola', crypt('rmmwzl', gen_salt('bf'))),
  ('Myeisha Octavia Kirana', crypt('iwqfbn', gen_salt('bf'))),
  ('Naira Issabililla Azzarah', crypt('vjlnfm', gen_salt('bf'))),
  ('Naufal Maulana', crypt('dqvwzw', gen_salt('bf'))),
  ('Nelson Fedora Setiawan', crypt('odprpp', gen_salt('bf'))),
  ('Nur Azizah Kholik', crypt('aiusvm', gen_salt('bf'))),
  ('Putra Erlangga Setiawan', crypt('aymvgv', gen_salt('bf'))),
  ('Reva Yunia Azzahra', crypt('ghorzv', gen_salt('bf'))),
  ('Silva Agustina Kalyla Ramadani', crypt('dwvwtg', gen_salt('bf'))),
  ('Sindy Aulia Putri', crypt('eqlojm', gen_salt('bf'))),
  ('Tyan Rahardian', crypt('egzbcj', gen_salt('bf'))),
  ('Viky Ade Willyam', crypt('marswp', gen_salt('bf')));

-- 9a (32 siswa)
INSERT INTO siswa_intervensi (name, kode_password_hash) VALUES
  ('Afika Aina Yusfa', crypt('nkkzen', gen_salt('bf'))),
  ('Ahmad Wasil Rifaldy', crypt('rdmrus', gen_salt('bf'))),
  ('Arjuna Vibhishana', crypt('uhbknc', gen_salt('bf'))),
  ('Arviantito Rajendra Athaillah', crypt('mbllfr', gen_salt('bf'))),
  ('Asha Nindya Pramusita', crypt('ypvqrz', gen_salt('bf'))),
  ('Audrey Zanetta Marantika', crypt('wmxavp', gen_salt('bf'))),
  ('Avrilia Porwanti', crypt('chhroa', gen_salt('bf'))),
  ('Azzahrah Rizki Aisyah Nur Rahma Abidin', crypt('binrfr', gen_salt('bf'))),
  ('Bayu Pratama', crypt('xjmymb', gen_salt('bf'))),
  ('Bima Juniarthah Putra Sadono', crypt('lsiifx', gen_salt('bf'))),
  ('Dafa Raka Ramadhani', crypt('agofaa', gen_salt('bf'))),
  ('Damas Saputra', crypt('ywobyl', gen_salt('bf'))),
  ('Dicky Mahardika', crypt('noodcp', gen_salt('bf'))),
  ('Dinar Nur Khoiriyah', crypt('tlvgqp', gen_salt('bf'))),
  ('Diva Rahayu', crypt('aorvbi', gen_salt('bf'))),
  ('Donyko Febrian Bimantara', crypt('fcgyyn', gen_salt('bf'))),
  ('Eka Bagus Pratama', crypt('qjnkjl', gen_salt('bf'))),
  ('Eloise Neyla Hapsari Putri', crypt('ssmita', gen_salt('bf'))),
  ('Endah Meisyaroh Tri Hidayah', crypt('nnwyvl', gen_salt('bf'))),
  ('Firjatul Firlyta Zahrina Zharfa Lis Shobirin', crypt('hzeewd', gen_salt('bf'))),
  ('Gabrill Yudistirtha Prasetya', crypt('iwifyz', gen_salt('bf'))),
  ('Gita Dewi Paramita', crypt('kvfptr', gen_salt('bf'))),
  ('Isnaini Dwi Kartini', crypt('fovvvr', gen_salt('bf'))),
  ('Jihan Safana Sufi', crypt('ywmwuf', gen_salt('bf'))),
  ('Joe Akbar Raditya Satriani', crypt('ldvikq', gen_salt('bf'))),
  ('Keyla Putri Hariyanto', crypt('fzycpr', gen_salt('bf'))),
  ('Kiran Humayraa Syauqi', crypt('plyqaj', gen_salt('bf'))),
  ('Muhamad Akbar Habibullah', crypt('ldzbvc', gen_salt('bf'))),
  ('Muhammad Octo Alif Vanza Dewa', crypt('nphcqt', gen_salt('bf'))),
  ('Mukhammad Marvin Yuliansyah', crypt('xhgngw', gen_salt('bf'))),
  ('Nadiva Zahira Ramadhani', crypt('kqxrrt', gen_salt('bf'))),
  ('Nilna Alfi Rizqiah', crypt('bcacvi', gen_salt('bf')));
